backend:
  name: git-gateway
  branch: master

media_folder: ""
public_folder: ""

collections:
  - name: "featured"
    label: "Featured"
    folder: "content/Featured"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Name", name: "title", widget: "string"}
      - { label: "Image", name: "image", widget: "file" }
  - name: "mains"
    label: "Mains"
    folder: "content/Mains"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "file" }
      - { label: "Short Description", name: "body", widget: "markdown" }
  - name: "fried"
    label: "Fried"
    folder: "content/Fried"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "file" }
      - { label: "Short Description", name: "body", widget: "markdown" }
  - name: "sides"
    label: "Sides"
    folder: "content/Sides"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "file" }
      - { label: "Short Description", name: "body", widget: "markdown" }
  - name: "bento"
    label: "Bento"
    folder: "content/Bento"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "file" }
      - { label: "Short Description", name: "body", widget: "markdown" }