backend:
  name: git-gateway
  branch: master

media_folder: ""
public_folder: ""

collections:
  - name: "featured"
    label: "Featured"
    folder: "content/Featured"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "file" }
  - name: "bento"
    label: "Bento"
    folder: "content/Bento"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Item Number", name: "itemnumber", widget: "string" }
      - {
          label: "Price (Number Only)",
          name: "price",
          widget: "number",
          value_type: "float",
        }
      - { label: "Short Description", name: "body", widget: "markdown" }
  - name: "sideDish"
    label: "Side Dish"
    folder: "content/sideDish"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Item Number", name: "itemnumber", widget: "string" }
      - { label: "Name", name: "title", widget: "string" }
      - {
          label: "Price (Number Only)",
          name: "price",
          widget: "number",
          value_type: "float",
        }
      - { label: "Short Description", name: "body", widget: "markdown" }
  - name: "rice"
    label: "Rice"
    folder: "content/Rice"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Item Number", name: "itemnumber", widget: "string" }
      - { label: "Name", name: "title", widget: "string" }
      - {
          label: "Price (Number Only)",
          name: "price",
          widget: "number",
          value_type: "float",
        }
      - { label: "Short Description", name: "body", widget: "markdown" }
  - name: "soup"
    label: "Soup"
    folder: "content/Soup"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Item Number", name: "itemnumber", widget: "string" }
      - { label: "Name", name: "title", widget: "string" }
      - {
          label: "Regular Price (Number Only)",
          name: "reg-price",
          widget: "number",
          value_type: "float",
        }
      - {
          label: "Large Price (Number Only)",
          name: "large-price",
          widget: "number",
          value_type: "float",
          required: false,
        }
      - { label: "Short Description", name: "body", widget: "markdown" }
  - name: "chickenspecialties"
    label: "Chicken Specialties"
    folder: "content/ChickenSpecialties"
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Item Number", name: "itemnumber", widget: "string" }
      - { label: "Name", name: "title", widget: "string" }
      - {
          label: "Full Price (Number Only)",
          name: "price",
          widget: "number",
          value_type: "float",
        }
      - {
          label: "Half Price (Number Only)",
          name: "halfprice",
          widget: "number",
          value_type: "float",
          required: false,
        }
      - { label: "Short Description", name: "body", widget: "markdown" }
